name: Sync from Account A
on:
  schedule:
    - cron: '0 * * * *'  # Hourly sync (UTC)
  workflow_dispatch:     # Manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout target repo (Account B)
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full history

      # Step 2: Configure git
      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Step 3: Add source repo (Account A)
      - name: Add Source Remote
        run: |
          git remote add source https://github.com/BawadharaniSree/MedNext2025.git
          git fetch source --tags  # Include tags

      # Step 4: Merge changes
      - name: Sync Changes
        run: |
          git checkout main
          git merge -X theirs source/main --allow-unrelated-histories --no-edit
          git push origin main
          git push --tags origin  # Push tags
